//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "board_settings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub board_id: i64,
    pub scans_per_send: i64,
    pub wifi_scan_time: i64,
    pub bluetooth_scan_time: i64,
    pub wifi_channel_scan_time: i64,
    pub bluetooth_channel_scan_time: i64,
    pub minimal_encounter_count: i64,
    pub min_rssi: i64,
    pub server_endpoint: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::boards::Entity",
        from = "Column::BoardId",
        to = "super::boards::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Boards,
}

impl Related<super::boards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Boards.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
