//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "boards")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub board_mac: i64,
    pub name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::board_data_records::Entity")]
    BoardDataRecords,
    #[sea_orm(has_one = "super::board_settings::Entity")]
    BoardSettings,
}

impl Related<super::board_data_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BoardDataRecords.def()
    }
}

impl Related<super::board_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BoardSettings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
