//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::board_data_records::Entity as BoardDataRecords;
pub use super::board_settings::Entity as BoardSettings;
pub use super::boards::Entity as Boards;
