#include "board_settings.h"
#include "config.h"

BoardSettings BoardSettings::loadDefaultSettings()
{
    return BoardSettings(SCANS_PER_SEND, WIFI_SCAN_TIME_MS, BLUETOOTH_SCAN_TIME_MS, CHANNEL_SCAN_TIME_MS, CHANNEL_SCAN_TIME_MS, MINIMAL_ENCOUNTER_COUNT, SERVER_ENDPOINT, EXTERNAL_ANTENNA, WIFI_SSID, WIFI_PASSWORD, PEAP, PEAP_IDENTITY, PEAP_USERNAME, PEAP_PASSWORD, MIN_RSSI);
}